# docker compose up -d
version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: querydsl
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: querydsl
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
